name: Build and Create Release & Tag
on:
  pull_request:
    types: [closed]
jobs:
  test:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: src/node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        working-directory: src
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Test
      #working-directory: src
      #run: npm test
  publish:
    name: Create Release & Tag
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Github Release Tag
        uses: rymndhng/release-on-push-action@v0.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT_TOKEN }}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        with:
          bump_version_scheme: norelease
