name: Lint & Test
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lint
      #  env:
      #    DB_DIALECT: ${{ secrets.DB_DIALECT }}
      #    FIRESTORE_CREDENTIAL: ${{secrets.FIRESTORE_CREDENTIAL}}
      #    AWS_CREDENTIAL: ${{secrets.AWS_CREDENTIAL}}
      # - run: npm run test
